[package]
name = "twilio_2"
version = "0.1.0"
authors = ["keatinge <willy.keatinge@gmail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
hyper-tls = "0.1.2"
url = "1.6"
serde_json = "1.0"
regex = "0.2.5"